apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.image.name }}-rule
  namespace: stage-org1
  labels:
    app: {{ .Values.labels.app }}
spec:
  host: {{ .Values.image.name }}-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: master
      labels:
        version: master
    - name: experimental
      labels:
        version: experimental