apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.image.name }}-service
  namespace: stage-org1
  labels:
    app: stage-org1
spec:
  host: {{ .Values.image.name }}-service
  subsets:
    - name: master
      labels:
        version: master
    - name: experimental
      labels:
        version: experimental