apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name:  {{ .Values.image.name }}-gateway
  namespace: stage-org1
  labels:
    app: {{ .Values.image.name }}
spec:
  selector:
    name: {{ .Values.image.name }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"