apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-service
  namespace: stage-org1
  labels:
    app: {{ .Values.labels.app }}
spec:
  hosts:
    - {{ .Values.image.name }}-service
  http:
    - route:
        - destination:
            host:  {{ .Values.image.name }}-service
            subset: experimental
          weight: {{ .Values.weight.experimental }}
          headers:
            request:
              add:
                version: experimental
        - destination:
            host:  {{ .Values.image.name }}-service
            subset: master
          weight: {{ .Values.weight.master }}
          headers:
            request:
              add:
                version: master
      retries:
        attempts: 3
        perTryTimeout: 1s
        retryRemoteLocalities: yes
      timeout: 5s