apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-vservice
  namespace: stage-org1
spec:
  hosts:
    - {{ .Values.image.name }}-service
  http:
    - route:
      - destination:
          host:  {{ .Values.image.name }}-service
          subset: experimental
        weight: {{ .Values.weight.experimental }}
      - destination:
          host:  {{ .Values.image.name }}-service
          subset: master
        weight: {{ .Values.weight.master }}