apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-service
  namespace: stage-org1
spec:
  hosts:
    - {{ .Values.image.name }}-service
  http:
  
    - fault:
        delay:
          fixedDelay: 1s
          percentage: 
            value: 30
      route:
        - destination:
            host:  {{ .Values.image.name }}-service
            subset: experimental
          weight: {{ .Values.weight.experimental }}
        - destination:
            host:  {{ .Values.image.name }}-service
            subset: master
          weight: {{ .Values.weight.master }}