apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-service
  namespace: stage-org1
  labels:
    app: {{ .Values.image.name }}
spec:
  hosts:
    - {{ .Values.image.name }}-service
  http:
    - route:
        - destination:
            host:  {{ .Values.image.name }}-service
            subset: experimental
          weight: {{ .Values.weight.experimental }}
        - destination:
            host:  {{ .Values.image.name }}-service
            subset: master
          weight: {{ .Values.weight.master }}
      fault:
        delay:
          fixedDelay: 10s
          percentage:
            value: 30
      retries:
        attempts: 3
        perTryTimeout: 1s
      timeout: 5s