apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-vservice
  namespace: stage-org1
spec:
  hosts:
    - {{ .Values.image.name }}-vservice
  http:
    - route:
      - destination:
          host: {{ .Values.image.name }}-service
          subset: experimental
        weight: 80
      - destination:
          host: {{ .Values.image.name }}-service
          subset: master
        weight: 20