---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: {{ .Values.deployment.labels.repoName }}-vservice
 namespace: {{ .Values.namespace.name }}
 labels:
   app: {{ .Values.image.name }}
spec:
 hosts:
   - "*"
 gateways:
   - expose-server-gateway
 http:
   - match:
     - uri:
         prefix: /{{ .Values.deployment.labels.repoName }}
     route:
       - destination:
           port:
             number: 80
           host: {{ .Values.deployment.labels.repoName }}-service